# 日志配置文件
# 支持开发和生产环境的不同日志级别和输出格式

version: 1
disable_existing_loggers: false

# 格式化器定义
formatters:
  # 详细格式（开发环境）
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s() - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  # 简洁格式（生产环境）
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  # JSON格式（用于日志聚合）
  json:
    format: '%(asctime)s'
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  # 访问日志格式
  access:
    format: '%(asctime)s - %(remote_addr)s - "%(request_line)s" %(status_code)s %(response_length)s "%(referer)s" "%(user_agent)s" %(request_time)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

# 处理器定义
handlers:
  # 控制台输出
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout
  
  # 应用日志文件
  app_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  # 错误日志文件
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8
  
  # 访问日志文件
  access_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: access
    filename: logs/access.log
    maxBytes: 10485760  # 10MB
    backupCount: 30
    encoding: utf8
  
  # 数据库日志文件
  db_file:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: detailed
    filename: logs/database.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  # 安全日志文件
  security_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/security.log
    maxBytes: 10485760  # 10MB
    backupCount: 30
    encoding: utf8
  
  # 性能日志文件
  performance_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/performance.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8
  
  # 系统日志（syslog）
  syslog:
    class: logging.handlers.SysLogHandler
    level: WARNING
    formatter: simple
    address: /dev/log
    facility: local0
  
  # 邮件通知（严重错误）
  email:
    class: logging.handlers.SMTPHandler
    level: CRITICAL
    formatter: detailed
    mailhost: localhost
    fromaddr: system@wlweb.local
    toaddrs:
      - admin@wlweb.local
    subject: '[CRITICAL] WLWeb System Error'

# 记录器定义
loggers:
  # 根记录器
  '':
    level: INFO
    handlers:
      - console
      - app_file
      - error_file
    propagate: false
  
  # 应用主记录器
  app:
    level: INFO
    handlers:
      - console
      - app_file
      - error_file
    propagate: false
  
  # FastAPI访问日志
  uvicorn.access:
    level: INFO
    handlers:
      - access_file
    propagate: false
  
  # FastAPI错误日志
  uvicorn.error:
    level: INFO
    handlers:
      - console
      - error_file
    propagate: false
  
  # 数据库相关日志
  sqlalchemy:
    level: WARNING
    handlers:
      - db_file
    propagate: false
  
  sqlalchemy.engine:
    level: WARNING
    handlers:
      - db_file
    propagate: false
  
  # Redis相关日志
  redis:
    level: WARNING
    handlers:
      - app_file
    propagate: false
  
  # 安全相关日志
  security:
    level: INFO
    handlers:
      - security_file
      - console
    propagate: false
  
  # 认证相关日志
  auth:
    level: INFO
    handlers:
      - security_file
      - app_file
    propagate: false
  
  # 性能监控日志
  performance:
    level: INFO
    handlers:
      - performance_file
    propagate: false
  
  # 业务逻辑日志
  business:
    level: INFO
    handlers:
      - app_file
      - console
    propagate: false
  
  # API请求日志
  api:
    level: INFO
    handlers:
      - access_file
      - app_file
    propagate: false
  
  # 文件上传日志
  upload:
    level: INFO
    handlers:
      - app_file
    propagate: false
  
  # 定时任务日志
  scheduler:
    level: INFO
    handlers:
      - app_file
    propagate: false
  
  # 第三方库日志控制
  requests:
    level: WARNING
    handlers:
      - app_file
    propagate: false
  
  urllib3:
    level: WARNING
    handlers:
      - app_file
    propagate: false
  
  # 开发调试日志
  debug:
    level: DEBUG
    handlers:
      - console
    propagate: false

# 根记录器配置
root:
  level: INFO
  handlers:
    - console
    - app_file
    - error_file